name: Keep Streamlit App Awake

on:
  schedule:
    # This runs every 6 hours. Format is: Minute Hour Day Month Day-of-week
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allows you to run it manually from the "Actions" tab

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit URL
        run: |
          curl -I https://cifar10-image-classifier.streamlit.app
